version: "3.9"

services:
  api:
    build: .
    container_name: squin-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env

  app:
    build: .
    container_name: squin-app
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      API_BASE: "http://api:8000"
    env_file:
      - .env
    depends_on:
      - api
